### ISSUE TITLE
Make day suggestion deterministic

### ISSUE THREAD

**Issue by lucaro** [dragbone/fg.pizzabot#3]
Currently, the suggested day is purely random in case there are multiple equally suited possibilities and multiple subsequent calls to `/bot pizza` might result in different suggestions. This could be avoided by fixing the seed of the random number generator for the week. I suggest the following solution:

```
import datetime
random.seed(datetime.datetime.now().isocalendar()[1])
```

**Comment by dragbone** [comment]
I agree that deterministic date selection is required. Requirements for a solution are (a) random (values from multiple random instances are not randomly distributed) and (b) should not change with new votes as long as it's still a valid choice.
